name: Deploy to AWS

on:
  push:
    branches:
      - qa
      - main

jobs:
  deploy:
    name: Deploy to AWS Instances
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to QA
        if: github.ref == 'refs/heads/qa'
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@52.201.212.184 "sudo rm -rf /var/www/html/*"
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa index.html ubuntu@52.201.212.184:/var/www/html/

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          for host in 52.91.181.82 44.211.241.2 3.227.22.30; do
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@$host "sudo rm -rf /var/www/html/*"
            scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa index.html ubuntu@$host:/var/www/html/
          done
