name: Deploy to AWS EC2

on:
  push:
    branches:
      - master  # Despliegue cuando haya un push a la rama master
      - main    # Si usas main, también lo puedes agregar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Clona el repositorio para obtener los archivos

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Cambia la región si es necesario

      - name: Sync files to EC2
        run: |
          scp -i "clave.pem" -o StrictHostKeyChecking=no -r ./ index.html ec2-user@<EC2-public-IP>:/var/www/html
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}

      - name: Restart Apache
        run: |
          ssh -i "clave.pem" -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} "sudo systemctl restart httpd"
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
