name: CI/CD Deployment with SSH

on:
  push:
    branches:
      - qa       # Rama para QA (pruebas)
      - main     # Rama para producción

jobs:
  deploy-qa:
    if: github.ref == 'refs/heads/qa'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to QA instance
        run: |
          scp -o StrictHostKeyChecking=no -r ./index.html ec2-user@52.55.80.185:/var/www/html
          ssh -o StrictHostKeyChecking=no ec2-user@52.55.80.185 "sudo systemctl restart httpd"

  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to production instances
        run: |
          # Instancia 1
          scp -o StrictHostKeyChecking=no -r ./index.html ec2-user@34.238.172.202:/var/www/html
          ssh -o StrictHostKeyChecking=no ec2-user@34.238.172.202 "sudo systemctl restart httpd"

          # Instancia 2
          scp -o StrictHostKeyChecking=no -r ./index.html ec2-user@3.229.142.222:/var/www/html
          ssh -o StrictHostKeyChecking=no ec2-user@3.229.142.222 "sudo systemctl restart httpd"

          # Instancia 3
          scp -o StrictHostKeyChecking=no -r ./index.html ec2-user@3.239.193.88:/var/www/html
          ssh -o StrictHostKeyChecking=no ec2-user@3.239.193.88 "sudo systemctl restart httpd"
